version: "3.8"

services:
  backend:
    build: ./
    ports:
      - 8080:8080
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/portfolio-user-service-db
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    depends_on:
      postgres-db:
        condition: service_healthy

  postgres-db:
    image: postgres:15-alpine
    container_name: user-service-db
    environment:
      POSTGRES_DB: portfolio-user-service-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d portfolio-user-service-db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: